name: Test

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Set environment variables
        run: |
          MONGO_URI=${{ secrets.MONGO_URI }}
          JWT_EXPIRE=${{ secrets.JWT_EXPIRE }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          BCRYPT_SALT_ROUNDS=${{ secrets.BCRYPT_SALT_ROUNDS }}
          MAIL_HOST=${{ secrets.MAIL_HOST }}
          MAIL_USER=${{ secrets.MAIL_USER }}
          MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
          APP_DOMAIN=${{ secrets.APP_DOMAIN }}
          NODE_TLS_REJECT_UNAUTHORIZED=${{ secrets.NODE_TLS_REJECT_UNAUTHORIZED }}
      - run: npm install
      - run: npm run test